name: Task list checks

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-all-tasks-completed:
    name: 'All tasks completed'
    uses: thrivadev/shared-workflows/.github/workflows/arc-task-list-check.yml@main
    secrets: inherit
